### ISSUE TITLE
Documentation improvement 

### ISSUE THREAD

**Issue by saharshbhansali** [proffapt/whapc#1]
It is very difficult to know what processes this script automates and what "work" it saves.
I'd suggest changing the description to something on the lines of, "saves time by automating a few processes related to Bluetooth audio devices".
That would give much more clarity to the purpose of the script.

**Comment by proffapt** [comment]
> It is very difficult to know what processes this script automates and what "work" it saves. I'd suggest changing the description to something on the lines of, "saves time by automating a few processes related to Bluetooth audio devices". That would give much more clarity to the purpose of the script.

urghh i am updating the README.md file, will do it withing some hours.

**Comment by saharshbhansali** [comment]
Yep, that would be great! I'll close the issue then. Thank you!
